<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <h3>
                    Alšova síň 1964
                </h3>
                <h4>
                    Jarmila Skalická
                </h4>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="alsovasin/alsovasin2.JPG" class="thumbnail">
                        <img src="alsovasin/alsovasin2.JPG" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="alsovasin/alsovasin3.JPG" class="thumbnail">
                        <img src="alsovasin/alsovasin3.JPG" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="alsovasin/alsovasin4.JPG" class="thumbnail">
                        <img src="alsovasin/alsovasin4.JPG" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="alsovasin/alsovasin5.JPG" class="thumbnail">
                        <img src="alsovasin/alsovasin5.JPG" style="height:150px">
                    </a>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">               
                    <p>                        
                        Malíř Vojta Nolč je členem skupiny „Máj", už tato příslušnost k určité generaci a
                        určité skupině by měla zaručovat kvalitu jeho práce a jeho uměleckou nosnost,
                        tak jak by to mělo předurčovat poslání tvůrčích skupin, které by tuto záruku měly nést.
                        Tvůrčí skupina „Máj" nevznikla z nějakého určitého výtvarného programu, tak jako např.
                        „Osma., a „Tvrdošíjní", ale vznikla tak jak tomu chtěla doba, tj. reakcí na určité
                        vulgarizující tendence ve výtvarném umění té doby. Máme na mysli navázání na zdravé 
                        české moderní tendence reprezentované např. jmény Kubišta, Guttfreund, Spála, Zrzavý,
                        Fr. Tichý.
                    </p><p>
                        Malíř Vojta Nolč je však jeden z těch, který i když znal velmi dobře základní prameny, 
                        přece jenom v jeho prvním období částečně vybočuje z tohoto rámce, protože formální
                        výslednici jeho prvního období možno zařadit do velké skupiny, která tvoří pod 
                        vžitým názvem „Part naive". Od této skupiny se malíř Nolč odlišuje natolik,
                        že jen některé vnější znaky této jeho tvorby prvního období by jej k této skupině 
                        zařazovaly.
                    </p><p>Převládá zde zásadně žlutá barva, která je zde široce hnětena až do vysokých past,
                        což je jedním ze znaků a také kontinuitou jeho tvorby současné. Mimo tento znak jsou to
                        i témata, která jsou dodnes totožná s tímto prvním obdobím, protože i když malíř Nolč
                        maloval krajinu nebo figuru, vždy byl tento model doprovázen určitým symbolem,
                        který ho doprovází i v současné tvorbě. Zdálo by se, že se Nolč v tomto  žlutém období
                        ustálil a fixoval svůj umělecký názor, zvláště, když ně  které jeho obrazy dosáhly zralosti
                        v tomto období. Bohužel toto období není na výstavě zastoupeno pro nedostatek prostoru.
                    </p><p>Okouzlen novými technickými možnostmi, novými barvivy a hmotami vrhá se malíř střemhlav
                        zcela po právu umělecké svobody do nového tvůrčího dobrodružství. Opouští zcela
                        nesentimentálně své žluté období a začíná malovat nové krajiny. Maluje je vrstvením
                        lazurových nátěrů, aby nechal působit jejich průzračnost. Opouští statický názor na
                        jediný úsek modelu krajiny, a tak jako třeba v kontrastu ke kubismu vznikl kynetický
                        futurismus, maluje oproti malému úseku celý krajinný dojem jeho denního zážitku,
                        vynechává horizontální rovinu a nechává se unášet citem. Kresebné zásahy pak jsou 
                        ještě ovlivněny malířem Dufym, a touto kresbou rozrušuje celistvost barevného zážitku. 
                        Celkový dojem pak působí jako perský koberec. Od koberce se však odlišuje neformálnosti 
                        celého zážitku a také tím, že nenazírá na krajinu s ptačí perspektivy, ale jsou v něm 
                        soustředěny nejen optické zážitky pohybové celého dne, ale hlavně citové. Je to asi obrácený 
                        postup v paralele, která nás právě napadá, když malíř Špála maloval v krajině a vítal pohyb 
                        větru a mraků, jimiž se zakrývá a odkrývá slunce a tento pohyb pomáhá pojímat krajinu 
                        nikoliv akademicky, ale zcela jinak, a to jen ryze výtvarnými prostředky barvou a tvarem, 
                        které mu pak dynamicky vytvářejí malířský prostor.
                    </p><p>Po tomto asi dvouletém období Nolč se nasycuje touto mozaikou pohybů a znovu se vrací
                        k pevnému tvaru, ponechávaje si však technické a barevné zkušenosti z předcházejícího období.
                        Vrací se ovšem k statičtějšímu tématu, které už zde po výtce dostává výraz symbolický,
                        tak jak tomu bylo ve žlutém období. Jako se díval celistvé na velkou krajinu transformovanou
                        svými malířskými možnostmi začíná malovat jen malý objekt, který ho zajímá svým tvarem.
                        Jsou to mušle, choroši a ořech. Záhy mu však nestačí jen převzatá barevná malba,
                        neboť by chtěl zachytit i pocity hmatové, zdánlivě nemalířské, a vrací se k pastě,
                        kterou zastupuje struktura a již jsme u posledních malířových obrazů, které zaujímají
                        většinu této expozice.
                    </p><p>Tyto obrazy by zasluhovaly širšího rozboru, neboť se dotýkají přímo současných problémů
                        nefigurální malby. Všimněme si však jen objektivních příčin a postupů jak došel Nolč k 
                        tomuto výrazu. I když zdánlivě jsou tyto obrazy nefigurativní přikládá jim malíř daleko
                        jiný význam, poněvadž jeho primérní zážitek se soustřeďuje na realitu a z ni i vyplývající 
                        životní zkušenosti. Všimněme si nejprve formální stránky: nápadný rys této tvorby je 
                        především v tom, že střídá kontrapunkticky hladkou malbu se strukturální, ponechávaje 
                        oběma polohám zářivost barevných loků. Rytmicky a kompozičně, jako by byl obraz bez hranic a 
                        mohl pokračovat do nekonečna; využívá této vlastnosti, že i když struktura působí velmi 
                        vehementně a naléhavě, v prvém momentu může divák reprodukovat dílo obráceně, tj. snažit se 
                        vnímat hladkou malbu, takže může získat překvapivě rytmus jiný.
                    </p><p>Obsah těchto obrazů je stále reálný a dává jejich formě konkrétní tvary ze zážitku životní 
                        zkušenosti a věcných tvarů, tak jak je tomu třeba u obrazů „Rychlořezný nůž", „Staré nástroje" nebo „Odtažitých tvarů", kde primérním principem tvarosloví byla architektonická torza starých architektur. Tyto věcné skutečnosti se snaží malíř rozvádět do filosofických rovin, tak jak je tomu u „Kamene mudrců" nebo obrazu „Pevný bod". Jinde opět včleňuje do těchto obrazů citové postřehy jako v obraze „Moře hučí v lastuře".
                        Je třeba říci, že tvůrčí proces se u malíře Vojty Nolče nezastavil, že si malíř otevřel a 
                        rozšířil nové cesty formální, které mu pomáhají v jeho manuálních možnostech vyššího 
                        citového dosahu. 
                    </p>     

                </div>                            
            </div>                            
        </div>
    </body>
</html>
