<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <h3>
                    Divadlo Rokoko 1957
                </h3>
            </div>
            <div class="row" >
                <div class="col-sm-4"> 
                </div>
                <div class="col-sm-4">
                    <p style="font-style: italic; font-size: larger"> 
                        Zabezpečit se proti nedosažitelnému<br/>
                        naše slabost<br/>
                        Zabezpečit se proti dosažitelnému<br/>
                        naše síla<br/>
                        Jiří Kolář: Mistr Sun o básnickém umění </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">               
                    <p>                        
                        Přítomná výstava je téměř po desíti letech prvou naší kolektivní exposicí,
                        jíž pomáhala sestavit toliko hlediska výtvarná. Manifestují se v ní vnitřní
                        vztahy našich mladých umělců k modernímu českému i světovému umění a navazuje
                        na dílo našich vůdčích zjevů umění 20. století, jejichž pravý význam umělecký
                        a cena kulturní byly v posledních letech zatemňovány.
                        Na štěstí odolalo tu mládí, které přirozeným pudem dopíditi se své vlastní
                        pravdy, nalezlo si ve výtvarném umění hodnoty, jež jsou společny
                        všem velkým dílům minulosti a jež možno vyjádřit formou danou přirozeným
                        vývojem i vlastním poznáním. Především je jim jasno, že skutečnost
                        a příroda mohou umělci dodat toliko výtvarné podněty a nemohou jim proto
                        sloužit jako model, vybízející oko výtvarníka k pouhému přepisu v plochu
                        plátna či objem plastiky. Odsuzují proto práci porot, které hodnotily jejich
                        dílo konfrontací se skutečnem. 
                    </p><p>
                        Autoři této výstavy chtějí tedy za prvé,
                        aby jejich malba a plastika působila, jako je tomu na příklad v hudbě,
                        vlastními, autonomními výtvarnými prostředky a měla sílu vyvolat podobné,
                        nevyslovitelné a nedefinovatelné pocity, jakými okouzluje každé velké umělecké
                        dílo. Věří, že se však k chápání a akceptování těchto hodnot musí divák
                        vychovat a mít k nim jisté musikální předpoklady. Za druhé usilují,
                        aby jejich dílo bylo výrazem citů současného člověka.
                        To je vlastně jejich jediné pojítko, když se jinak nikdo z nich neztotožňuje
                        s druhým ve společně závazných názorech a kolektivně platné slohové formě
                        a respektuje každého v jeho tvůrčí svobodě a předem danými zákony nepoutané
                        individuálnosti. 
                    </p><p>
                        Jejich tvorbě se také vytýkala závislost na západních vzorech.
                        Ano, tvůrci této výstavy hlásí se k dílu Pabla Picassa, Henri Matisse,
                        André Deraina, stejně tak jako k našemu Bohumilu Kubištovi, Emilu Fillovi,
                        Janu Zrzavému, Rudolfu Kremličkovi, Josefu Šímovi a Františku Tichému,
                        jejichž charakter stojící v rozporu s měšťáckými názory, jeví se jim stejně
                        hrdinný, jako kdysi vlastenecký postoj Mánesův a Alšův. Hlásí se tedy
                        k tradici vybojované spolkem Mánes a jeho Volnými směry a chtějí navazovat tam,
                        kde se v tomto směru před lety skončilo. Ano, jejich dílo je závislé na jistých
                        vzorech (jakoby umění mohlo být vůbec bez závislosti na díle předchůdců),
                        ale jsou přesvědčeni, že tu není více závislostí, než kolik převzal
                        Mistr Vyšebrodský před staletími od Mistra z Klosterneuburgu,
                        kolik je závislý v 18. století Jan Kupecký na díle Fra Vittore Ghislandiho,
                        Karel Purkyně na Rembrandtovi a Courbetovi, Josef Mánes na Corneliovi,
                        Richterovi a Schwindovi. U nich to naše umělecká historie zcela obecně 
                        shledává jako ctnost a velkou přednost, když se dovedli
                        „v osudnou hodinu našeho vývoje" zapojit na světové proudy, ale mladým 
                        se souvislost se světovými umělci a domácím pokrokovým uměním nedovolovala.
                        Jsou hrdi, že se liší od svých školských učitelů a že se s nimi nesrovnávají,
                        neboť je to dokladem, že jdou dopředu. 
                    </p><p>
                        Tato vůle mířit svým dílem vpřed 
                        je jim tedy společným programem a není v rozporu s ničím v minulosti pokrokovým.
                        Nechtějí naše klasiky kopírovat, ale následovat je v jejich tvůrčí odvaze,
                        jak,to na příklad krásně vyjádřil Mikoláš Aleš, když mluvil o budoucnosti
                        svého díla: „... není dopověděno, musí být pokračováno. Kdo bude pokračovat,
                        jest ovšem pro dnes otázka. Někdo bude pokračovat, ale bude to již zase
                        modernější a potom, co jsme my vlastně prožívali, nebude již vědět ..." 
                        V této vůli být ve svém výraze novějšími a tedy podle citátu z Alše „modernější",
                        spočívá tedy třetí vlastnost jejich práce a jejich společný úkol.
                        Manifestem tohoto názoru je tato výstava. 
                    </p><p>
                        František Dvořák 
                    </p>
                </div>                            
            </div>                            
        </div>
    </body>
</html>
