<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <h3>
                    Galerie bratří Čapků 1966
                </h3>

            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galeriebratricapku/galeriebratricapku1.JPG" class="thumbnail">
                        <img src="galeriebratricapku/galeriebratricapku1.JPG" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galeriebratricapku/galeriebratricapku2.JPG" class="thumbnail">
                        <img src="galeriebratricapku/galeriebratricapku2.JPG" style="height:150px">
                    </a>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-8">               
                    <h3>
                        Malířovo přiznání     
                    </h3>                        
                    <p style="font-style: italic">
                        <span style="font-weight: bold">A.P. </span> Již více než pět let se pohybujete v oblasti strukturálních znaků. 
                        Jak jste kdy přistupoval k řešení? 
                    </p>
                    <p>
                        <span style="font-weight: bold">V. N. </span> Výsledky první fáze svých pokusů jsem předložili, březnu 1964 v Alšově
                        síni. Zájem o struktury pomohl mi objevit krása přírodních věcí, ořechů,
                        chorošů, mušlí nebo kamenů a jejich povrchu. Tento povrch je velmi dramatický:
                        vrásněn zevnitř jako odpověď na zásahy okolí.
                    </p>
                    <p style="font-style: italic">
                        <span style="font-weight: bold">A.P. </span> Váš zájem o přírodní a organické, který je paralelní i Vašemu impulsivnímu
                        založení, narůstal v dalším období jaksi v pozadí, protože vidím, jak najednou
                        vystupují do popředí fragmenty nástrojů a architektur, záznamy fungující 
                        v obraze jako znaky.
                    </p>
                    <p>
                        <span style="font-weight: bold">V. N. </span> Při hledání nových námětů jsem se dostával stále více do sféry archaického
                        světa, ať už to byla stará nářadí, nebo torsa archeologických vykopávek, jejichž
                        pozoruhodné povrchy utvářela staletá koroze. To na jedné straně. Na druhé straně 
                        to byl svět značek na staré keramice nebo řezaném skle, svět znakového písma, 
                        který mě přitahoval. Všimněte si, jak nápisy tesané nebo malované na starých 
                        orientálních obrazech zvyšují tajemné kouzlo. A pak značky krajinných útvarů, 
                        květů, dračích vzorů, jež se na čínských a japonských svitcích prolínají s
                        kaligrafií! A což staré mince a medailony, pečetě s rozrušeným povrchem a se 
                        zašlými hlavami panovníků. To vše mě ohromně inspirovalo. 
                    </p>
                    <p style="font-style: italic">
                        <span style="font-weight: bold">A.P. </span> Od úlomků jste se dostal k zápisu a torsa se stala samostatnými objekty. 
                        Jak jste ony podněty archaického světa dále zpracoval, a vůbec, co přinášíte 
                        nového? 
                    </p>
                    <p>
                        <span style="font-weight: bold">V. N. </span> Na to nemohu odpovědět jednou větou. Za prvé jsem hledal malířský materiál, 
                        který by mi umožnil přímé využití přírodních procesů nebo aspoň jejich 
                        symbolisování. Bylo to staré dřevo, upravené k lidským funkcím, v němž jsem 
                        spatřoval ideální materiál. Výplně vysloužilých hospodářských strojů, dřevo 
                        vyžrané proudy zrní, písku a vody jsem vzal jako podklad malby. Využíval jsem 
                        struktur obsažených ve dřevě a vytvářel vlastní struktury. K barevným strukturám 
                        z emailů, laků a olejů jsem připojil struktury a znaky lité z bronzu a aluminia. 
                        Druhé moje novum je grafický obraz. Souvislosti mezi podklady (dřevo — papír), 
                        znaky a strukturami jsou myslím zřejmé.
                    </p>
                    <p style="font-style: italic">
                        <span style="font-weight: bold">A.P. </span> Vaše velké grafiky vlastně dovádějí do krajního důsledku dekorativní funkci 
                        závěsné grafiky, mohu-li tak nazvat onu nekomorní polohu. Avšak jak tyto velké 
                        formáty tisknete?
                    </p>
                    <p>
                        <span style="font-weight: bold">V. N. </span> Staré přátelství s tiskařem A. Černým, přítelem a spolužákem velkého 
                        českého malíře Karla Černého (pouhá shoda jmen), který tiskl jeho grafické 
                        prvotiny, mne vedlo k tisku. Tisk je mi velmi blízký, neboť již v roce 1959 
                        jsem měl samostatnou výstavu monotypů. Bohaté tiskařské zkušenosti a všestranná 
                        znalost různých tiskařských technik A. Černého mi umožňují odbornou realizaci. 
                        V podstatě obnovujeme starou praxi přímé spolupráce výtvarníka s uměleckým 
                        tiskařem. Využíváme všestranně nejrůznějších tiskařských technik, zejména 
                        reliéfního tiskařského procesu, ať už omítkového reliéfu, reliéfního barevného 
                        papírořezu, plastického hloubkového tisku apod. Nejde nám však jen o vytváření 
                        monotypů, nýbrž také o tisk různých variací na tentýž námět a o opakovatelnost 
                        rozmnožování ve smyslu běžné grafiky. Jedním z našich cílů je „grafický obraz",
                        ke kterému naše úsilí směřuje.
                    </p>
                    <p style="font-style: italic">
                        <span style="font-weight: bold">A.P. </span> Vyjadřujete se znakově a vycházíte ze strukturálního pocitu obrazu a 
                        objektu. Nebojíte se, že Vám určitá část kritiky vytkne vývojové zpoždění čili
                        neaktuálnost a že Vám „čistí" strukturalisté budou zazlívat věcnou asociabilitu? 
                    </p>
                    <p>
                        <span style="font-weight: bold">V. N. </span> O tom nepřemýšlím. Mám svoje lásky a chci říci svou pravdu. 
                        A potom, aktuálnost je velmi relativní. 
                    </p>
                    <p>A. POHRIBNÝ 
                    </p>
                </div>                            
            </div>                            
        </div>
    </body>
</html>
