<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="page-header">
                <h1>Vojta Nolč <small><br/>Malíř a grafik, zakládající člen skupiny Máj 57</small></h1> 
            </div>
            <h4>
                * 18. března 1912, Linec   &nbsp;&nbsp;&nbsp; † 27. března 1989, Nová Ves pod Pleší
            </h4>
            <div class="row">
                <div class="col-md-6">
                    <a href="portrety/Portret1.jpg"><img src="portrety/Portret1.jpg" height="300" alt=""/></a>                                        
                </div>
                <div class="col-md-6">
                    <a href="portrety/Portret2.jpg"><img src="portrety/Portret2.jpg" height="300" alt=""/></a>                  
                </div>
            </div>
            <h4>
                Samostatné výstavy:
            </h4>  
            <ul>
                <li>                  
                    1959 Divadlo Rokoko, Praha (kat. Fr. Dvořák)
                </li><li>          
                    1964 Alšova síň, Praha (kat. J. Skalická)
                </li><li>          
                    1966 Galerie bratří Čapků, Praha (kat. A. Pohribný) 
                </li><li>          
                    1992 V. N. Žlutě, Galerie Růžový kopeček, Cheb
                </li><li>          
                    1997 V. N. Pozůstalost, Zámecká galerie města Kladna
                </li>          
            </ul>
            <h4>
                Kolektivní výstavy:   
            </h4>
            <ul>
                <li>   
                    1957 Mladé umění, Tvůrčí skupina Máj, Obecní dům, Praha (kat. Fr. Dvořák, M. Chlupáč)
                </li><li>  
                    1958 2. výstava skupiny Máj 57, Palác Dunaj, Praha
                </li><li>  
                    1958 Wystawa grupy „maj 57“, Galeria Sztuki Nowoczeskej, Varšava, Polsko (kat. M. Chlupáč)
                </li><li>  
                    1961 Skupina Máj, Poděbrady
                </li><li>  
                    1962 Jaro 62, Mánes, Praha
                </li><li>  
                    1964 Skupina Máj, Nová síň, Praha
                </li><li>  
                    1964 Skupina Máj, Městské muzeum, zámek, Teplice
                </li><li>  
                    1966 Jaro 66, Mánes, Praha 
                </li><li>  
                    1967 Prager Künstler, Galerie Maerz, Linec, Rakousko
                </li><li>  
                    2003 – 2004 Umění je abstrakce. Česká vizuální kultura 60. let,
                    Jízdárna Pražského hradu, Muzeum umění Olomouc,
                    Moravská galerie v Brně, Galerie U Bílého jednorožce,
                    Klatovy (kat. Z. Primus)
                </li><li>  
                    2007 Skupina Máj 57. Úsilí o uměleckou svobodu na přelomu 50. a 60. let,
                    Císařská konírna Pražského hradu (kat. A. Primusová, M. Klimešová)
                </li><li>  
                    2009 Roky ve dnech, GHMP Městská knihovna
                </li>
            </ul>
        </div>
    </body>
</html>
