<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Kontakt</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">                
                <div class="col-md-16">
                    Pokud vlastníte nějaké dokumenty, fotografie nebo jiný
                    materiál o malíři Vojtu Nolčovi, kontaktujte prosím
                    správce tohoto webu.
                </div>
                            <hr/>
            </div>

            <div class="row">
                <div class="col-md-16">
                    <!-- BLUEBOARD MAILFORM-->
                    <!-- !!!!!!!!!!!!!!!!! login: jiri.danecek !!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
                    <iframe allowtransparency="true" frameborder="0" scrolling="no" width="330" height="140" src="http://miniaplikace.blueboard.cz/mailform.php?id=250942"></iframe>
                    <!-- BLUEBOARD MAILFORM KONEC-->
                </div>
            </div>
        </div>
    </body>
</html>