<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/objekty/Objekt1.jpg" class="thumbnail">
                        <p></p>    
                        <img src="galerie/objekty/thumbs/Objekt1.jpg" alt="Objekt" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/objekty/Zeleny_kruh.jpg" class="thumbnail">
                        <p>Zelený kruh, kombinovaná technika, 120 x 75, 1965</p>    
                        <img src="galerie/objekty/thumbs/Zeleny_kruh.jpg" alt="Objekt" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/objekty/Objekt3.jpg" class="thumbnail">
                        <p></p>    
                        <img src="galerie/objekty/thumbs/Objekt3.jpg" alt="Objekt" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/objekty/Objekt4.jpg" class="thumbnail">
                        <p></p>    
                        <img src="galerie/objekty/thumbs/Objekt4.jpg" alt="Objekt" style="height:150px">
                    </a>
                </div>
            </div>
        </div>            
    </body>
</html>
