<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Zamyslena.jpg" class="thumbnail">
                        <p>Zamyšlená, monotyp, 70x55 cm, 1957</p>    
                        <img src="galerie/obrazy/thumbs/Zamyslena.jpg" alt="Zamyšlená" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Mesto_s_maringotkou.jpg" class="thumbnail">
                        <p>Město s maringotkou, olej na plátně, 90 x 110 cm, 1959</p>    
                        <img src="galerie/obrazy/thumbs/Mesto_s_maringotkou.jpg" alt="Město s maringotkou" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Musle.jpg" class="thumbnail">
                        <p>Mušle, kombinovaná technika, 60 x 80 cm, 1962</p>    
                        <img src="galerie/obrazy/thumbs/Musle.jpg" alt="Mušle" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Cinsky_motiv.jpg" class="thumbnail">
                        <p>Čínský motiv, monotyp, 60 x 40 cm, 1963</p>    
                        <img src="galerie/obrazy/thumbs/Cinsky_motiv.jpg" alt="Čínský motiv" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Kamen_mudrcu.jpg" class="thumbnail">
                        <p>Kámen mudrců, kombinovaná technika, 122 x 45 cm</p>    
                        <img src="galerie/obrazy/thumbs/Kamen_mudrcu.jpg" alt="Kámen mudrců" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Kralovske_klenoty.jpg" class="thumbnail">
                        <p>Královské klenoty, kombinovaná technika, 48 x 123 cm,  1963</p>    
                        <img src="galerie/obrazy/thumbs/Kralovske_klenoty.jpg" alt="Královské klenoty" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Osudny_nastroj.jpg" class="thumbnail">
                        <p>Osudný nástroj, kombinovaná technika, 50 x 95 cm, 1963</p>    
                        <img src="galerie/obrazy/thumbs/Osudny_nastroj.jpg" alt="Osudný nástroj" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Cerveny_bod.jpg" class="thumbnail">
                        <p>Červený bod, monotyp, 100 x 70 cm, 1964</p>    
                        <img src="galerie/obrazy/thumbs/Cerveny_bod.jpg" alt="Červený bod" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Zena.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Zena.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Bludiste.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Bludiste.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Cerveno_modra.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Cerveno_modra.jpg" alt="" style="height:150px">
                    </a>
                </div>                
                <div class="col-md-4">
                    <a href="galerie/obrazy/Kamen_mudrcu.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Kamen_mudrcu.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Karneval.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Karneval.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Krajina.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Krajina.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Loze.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Loze.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Modra.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Modra.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/More.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/More.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Musle_2.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Musle_2.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Ostrovy.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Ostrovy.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Pierot.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Pierot.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Ptaci.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Ptaci.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Puzzel.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Puzzel.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/S_kvetinou.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/S_kvetinou.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Tanec.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Tanec.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/Tri_akty.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Tri_akty.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Umele_kvetiny.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Umele_kvetiny.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Umeni_je_abstrakce.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Umeni_je_abstrakce.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/obrazy/V_cele.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/V_cele.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/V_zelene.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/V_zelene.jpg" alt="" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/obrazy/Naves.jpg" class="thumbnail">
                        <img src="galerie/obrazy/thumbs/Naves.jpg" alt="" style="height:150px">
                    </a>
                </div>

            </div>
        </div>            
    </body>
</html>
