<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/local.css">
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h3>
                        Vojta Nolč - Pozapomenutý malíř
                    </h3>
                    <h4>
                        Radek Wohlmuth; Labyrint Revue : časopis pro kulturu / Joachim Dvořák, Č.4 (1996), s.42-43   
                    </h4>
                </div>
            </div>
            <div class="row top10">
                <div class="col-md-8">
                    <a href="pozapomenutymalir/pozapomenutymalir1.JPG">
                        <img src="pozapomenutymalir/pozapomenutymalir1.JPG"  class="catalogpage">
                    </a>
                    <a href="pozapomenutymalir/pozapomenutymalir2.JPG" >
                        <img src="pozapomenutymalir/pozapomenutymalir2.JPG"  class="catalogpage">
                    </a>
                    <a href="pozapomenutymalir/pozapomenutymalir3.JPG" >
                        <img src="pozapomenutymalir/pozapomenutymalir3.JPG"  class="catalogpage">
                    </a>
                    <hr/>
                </div>
            </div>            
            <div class="row top10">
                <div class="col-md-8">
                    <p>
                        Československo bylo v padesátých letech zemí, která dělala co mohla,
                        aby překonala mílovými kroky vzdálenost, dělící ji od vytouženého přívlastku
                        socialistická, z něhož se pak ještě dlouho nemohla vzpamatovat.
                        Byla to země úspěchů - úspěšného přídělového systému, úspěšné první pětiletky,
                        úspěšné měnové reformy, úspěšných politických procesů i úspěšných partyzánských
                        velkofilmů. Existovala ve světě, který se narodil v Rusku roku 1917 a končil
                        pět kilometrů za Chebem. Opratě tady byly utažené nakrátko a „ochranný"
                        centrální dozor se týkal všeho, všech a neustále.
                    </p> <p>
                        Tato doba temna se samozřejmě nevyhýbala ani umění.
                        Žďanovovská doktrína socialistického realismu jasně definovala jedinou možnou,
                        pravdivou a nezatíženou cestu „vpřed" a nekompromisně ji „očišťovala"
                        od veškerých buržoazních vlivů. Přesto, anebo právě proto, padesátá léta 
                        stvořila celou řadu ryzích uměleckých osobností. Tito umělci se,
                        v naprosté většině případů, nemohli plně realizovat ve svém aktuálním 
                        čase a jejich prvá veřejná vystoupeni přišla teprve s postupným
                        uvolňováním kulturní politiky na přelomu let 1957-1958, ale tehdy naráz
                        nastoupila silná několikagenerační vlna, jejíž představitelé se dodnes
                        řadí mezi elitu našeho výtvarného umění.
                    </p> <p>
                        V podstatě ihned a natrvalo se
                        ovšem podařilo prosadit jen několika málo výtvarníkům - zejména těm mladším.
                        Mnozí, tak jak se objevili, zase se ztratili. Příčin bylo více, svou roli
                        sehrál jisté i zmíněný posun v čase, ale nejen ten. Většinou se jednalo
                        o důvody zcela prozaické. Někteří z nich emigrovali,
                        jiní zanechali tvorby nebo dožili svůj život v ústraní.
                        Několik nadějných výtvarníků předčasně zemřelo, část prostě jen neměla štěstí.
                        Ale přesto, že se v těchto případech téměř automaticky hovoří o osobní prohře,
                        faktem nicméně zůstává, že i když oni sami snad „nevydrželi" - jejich dílo,
                        vnímané prizmatem uplynulého času, se stále vyznačuje nábojem,
                        hloubkou a nespekulativní opravdovostí, která nám v dnešní době mnohdy chybí.
                        Uchovává si svou logiku a přesvědčivost, s jakou se také příliš často
                        nesetkáváme a postrádáme ji čím dál více i u některých našich současníků.
                        Snad proto stojí za to se k některým z těchto výtvarníků vrátit,
                        připomenout jejich jméno, krom jiného i z toho důvodu, že mnozí z nich
                        na svou šanci zatím stále ještě čekají.
                    </p> <p>
                        Jedním z takových téměř zapomenutých
                        je také malíř a grafik Vojta Nolč. Narodil se 18. března 1912 v Linci,
                        v Horním Rakousku. Pokřtěn byl podle římsko-katolického obřadu a své
                        jméno - Vojtech (Adalbert) dostal po otci. Nolč pocházel z rodiny se
                        silnou řemeslnickou tradicí, od které se jako jediný profesně odchýlil.
                        Poté, co rodina přesídlila do Čech, studoval na Německé obchodní akademii
                        v Plzni, kde v roce 1931 odmaturoval. Od této doby pracoval jako soukromý
                        úředník. Po svém přestěhování do Prahy začal soukromě studovat kresbu,
                        malířské a grafické techniky u prof. Aloise Boháče a prof. Vladimíra Pukla.
                        Jako malíř se Nolč zařadil do výtvarného s života v rámci umělců sdružených
                        v tvůrčí skupině „Máj 57", mezi jejíž zakládající členy patřil.
                        První výstava skupiny se uskutečnila v roce 1957 v Obecním domě a
                        Nolč se při ní ocitl ve společnosti takových osobností,
                        jakými jsou například Robert Piesen, Jiří Richard Fremund,
                        Libor Fára, Miloš Chlupáč, Zdeněk Palcr nebo Andrej Bělocvětov.
                        (Pozn. redakce - A. Bělocvětovovi jsme věnovali barevnou galerii a portrét
                        v Labyrintu Č. 8. roč. 1993.)
                    </p> <p>
                        Výstava se jmenovala „Mladé umění"
                        a v naprosté většině představovala obrazy čerstvých třicátníků.
                        Vojta Nolč byl se svými pětačtyřiceti lety zdaleka nejstarší.
                        Představoval se tu osmi oleji a dvěma monotypy ze svého žlutého období.
                        Pro Nolče byla tato kolektivní výstava jednou z nejdůležitějších,
                        protože i když byla výtvarným projevem velmi široká,
                        dala mu jasná názorová východiska a i předpoklady pro další samostatnou
                        tvorbu.
                    </p> <p>
                        Vystoupení skupiny „Máj 57" patřilo k nevýznamnějším výtvarným
                        počinům své doby. Její členy stmeloval odpor proti dogmatům akademismu,
                        direktivní naturalistické manýře a dohledu oficiálních porot více,
                        než společná umělecká východiska. Otevřeně kritizovali stávající situaci
                        a požadovali právo na individualitu, moderní výraz a svobodu uměleckého
                        projevu. Proto se není ani čemu divit, že záhy dostavila tvrdá kritika
                        skupiny ze strany ÚV SČSVO, ale to už byl průlom učiněn a „Máj 57"
                        pokračoval ve své činnosti.
                    </p> <p>
                        Vojta Nolč se s myšlenkami skupiny plně
                        ztotožnil a vystavoval pravidelně na všech jejích akcích.
                        Už následujícího roku (1958) to bylo v pražském paláci Dunaj
                        na Národní třídě a dále následovaly výstavy ve Varšavě, Poděbradech,
                        v Nové síni v Praze, na zámku v Teplicích a nakonec v roce 1967
                        v Nolčově rodném městě Linci, což byla zároveň jeho poslední výstava
                        v životě.
                    </p> <p>
                        Svou první samostatnou výstavu Nolč instaloval v roce 1959
                        ve foyeru divadélka Rokoko na Václavském náměstí.
                        Na vernisáži promluvil dvorní teoretik „Máje 57" František Dvořák
                        a kromě kolegů ze skupiny tu byl také například František Tichý,
                        Max Švabinský, ale i mladý Jiří Sozanský.
                        Nolč představil svůj výběr kreseb a monotypů z let 1954-58.
                        Jeho projev se vyznačoval jednoduchou působivou kresbou
                        a jasnou barevností. Nekomplikovaný, hravý výraz s téměř dětsky
                        tříděnými detaily, přehledné rozvržené tvary a atmosféra zářivého
                        svátečního poklidu, které jej formálně přibližují sféře naivního
                        malířství, plně odpovídají myšlence osobité citové výrazovosti
                        „Máje 57".
                    </p> <p>
                        V této době vrcholilo Nolčovo osobité žluté období,
                        jímž se ode všech odlišoval a plynně navazoval na tvorbu svých oblíbenců
                        - Gauguina a van Gogha. Své práce značí povangoghštělou signaturou Vojta
                        a po Gauguinově příkladu opouští ve svých sedmačtyřiceti letech
                        zajištěné úřednické místo, aby se mohl plně věnovat malování.
                        Maluje zejména krajiny inspirované atmosférou zapomenutých,
                        „bohem požehnaných" slovenských vesnic, jihomoravskou Telčí
                        a panenským prostředím v okolí Stříbra, ale z tohoto období
                        pochází také například „žlutý" portrét Roberta Piesena.
                    </p> <p>
                        V následujících letech Vojta Nolč opouští své žluté období.
                        Na čas se hlavními náměty jeho obrazů stávají továrenský civilismus
                        a ospalá poetika maloměsta, ale autor začíná brzy malovat nové krajiny.
                        Vynechává linii horizontu, nezobrazuje statický výsek,
                        ale maluje celý krajinný, pohybový i citový dojem denního zážitku,
                        takže výsledek „působí jako perský koberec".
                        Vrstvené lazury jen zdůrazňují jejich průzračnost.
                    </p> <p>
                        Když Nolč „vyčerpal" možnosti této krajinné ornamentiky,
                        vrací se opět k jasné definovanému obrysovému tvaru.
                        Nyní maluje naopak jen docela malé předměty,
                        které jej vzrušují svým tvarem a povyšuje je do symbolické roviny.
                        Jedná se zejména o mušle a ořechy. Začíná opět pracovat s pastami
                        a zachycuje tak zároveň hmatový dojem. Charakteristické je
                        pro něho střídání struktur a hladké malby, téměř
                        monochromní pojetí a zjevná nefiguralita.
                        Obsah těchto obrazů je stále reálný, objevují se však i motivy historické a
                        mytologické - Staré nástroje", „Královské klenoty", „Kámen mudrců".
                        Výsledky své práce Nolč prezentoval na další samostatné výstavě,
                        tentokrát Alšově síni v Praze roku 1964. Bezprostředně po jejím ukončení
                        přišla z oddělení moderního umění NG nabídka na předložení
                        čtyř vystavených prací k nákupu.
                    </p> <p>
                        Sféra archaického světa,
                        torza archeologických vykopávek, znakové písmo a kouzlo orientu Nolče
                        nadále neopouštějí. Pro své obrazy hledá materiál, ve kterém je toto vše
                        již obsaženo a nachází jej ve starém dřevě,
                        výplních vysloužilých hospodářských strojů, oprýskaných dveřích
                        i pořezaných deskách stolů. Využívá struktur ve dřevě, vytváří struktury
                        vlastní, kombinuje emaily, laky, oleje, litý bronz a aluminium.
                        Spolu s Mikulášem Medkem experimentuje LSD a pod rukama mu vznikají
                        organické halucinogenní abstrakce, které spolu s velkými grafickými
                        obrazy vystavuje na své poslední autorské výstavě v pražské Galerii
                        bratří Capků v roce 1966.
                    </p> <p>
                        Své ohromné grafické listy Nolč tiskl se svým přítelem Adolfem 
                        Černým, s nímž navázal na tradiční spolupráci výtvarníka a uměleckého tiskaře.
                        Právě jeho schopnosti mu umožnily všestranné vyžití nejrůznějších
                        tiskařských technik, zejména reliéfního tiskařského procesu.
                    </p> <p>
                        Od začátku sedmdesátých let se postupně zhoršuje Nolčův zdravotní stav.
                        Pokud může, opouští se svou druhou, o devětadvacet let mladší ženou
                        Táničkou Prahu a žije v oblíbeném kraji nedaleko západočeského Stříbra.
                        Zde vytváří asambláže, předznamenané už objekty na výstavě v Galerii
                        bratří Čapků a maluje obrazy na sklo.
                        Lidové prostředí, ze kterého vyšel, a které mu bylo vlastní po celou
                        u dobu, se nyní stává dominantním. Zřetelněji než kdy jindy se v jeho
                        životě i umění uplatňuje také náboženství.
                    </p> <p>
                        Vojta Nolč zemřel 27. března 1989 v sanatoriu Nová Ves.
                        Jeho žena Tánička spáchala sebevraždu rok po jeho smrti.
                    </p>        
                </div>
            </div>
        </div>
    </body>
</html>
