<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <link rel="stylesheet" href="/css/local.css">
        <link rel="stylesheet" href="/css/local.css">
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h3>
                        Roky ve dnech - české umění 1945-1957<br/>
                        GHMP Městská knihovna 2010
                    </h3>
                    <h4>
                        Marie Klimešová 
                    </h4>   
                </div>
                <div class="col-md-2">
                    <img src="rokyvednech/rokyvednech.gif" style="width:120px" />    
                </div>
            </div>
            <div class="row">        
                <div class="col-md-8">
                    <hr/>
                </div>
            </div>
            <div class="row top10">
                <div class="col-md-4">
                    <a href="galerie/villon/Motlitba_k_matce_bozi.jpg" class="thumbnail">
                        <p>Modlitba k matce boží - A s vírou tvou já žíti a zemřít chci, akvarel, papír, 60 x 42 cm, 1955</p>
                        <img src="galerie/villon/thumbs/Motlitba_k_matce_bozi.jpg" alt="Villon" style="height:150px">
                    </a>
                </div>                
            </div> 
            <div class="row top10">
                <div class="col-md-8">
                    <p>
                        Spiritualita, aniž by musela být přímo spojována s biblickými motivy,
                        tehdy prostupovala různými způsobem celou škálu autorských projevů a
                        tematických okruhů navzdory názorovým odlišnostem i generační příslušnosti.
                        Velké akvarely, které v roce 1955 vytvořil dnes málo známý Vojtěch Nolč (1912-1989),
                        kupříkladu představují specifickou reflexi Villonova Velkého testamentu.
                        Nolč sice v mládí prošel soukromým výtvarným školením a měl už tehdy za sebou určitý vývoj,
                        pracoval ale jako bankovní úředník a upozornil na sebe až v souvislosti
                        se svou aktivitou ve skupině Máj 57. Dva villonovské akvarely,
                        jakýsi autorův horror vacui, jsou zaplněny mnoha symboly víry, smrti a tělesnosti.
                        V rámci dobové české neoficiální produkce působí značně nekonvenčně -
                        jako interpretace klasického literárního textu z pozice svátečního malíře,
                        který si může dovolit se nezatíženě a bez jakýchkoli pravidel vyjadřovat k silnému podnětu.                
                    </p>
                </div>
            </div>
            <div class="row">        
                <div class="col-md-8">
                    <hr/>
                </div>
            </div>
            <div class="row">        
                <div class="col-md-4">
                    <a href="galerie/obrazy/Autoportret.jpg" class="thumbnail">
                        <p>Autoportrét, olej na plátně, 75 x 99 cm</p>
                        <img src="galerie/obrazy/thumbs/Autoportret.jpg" alt="" style="height:150px">
                    </a>
                </div>
            </div>
            <div class="row">        
                <div class="col-md-8">
                    <p>
                        Expresionismus nebo fauvismus využili počátkem padesátých let k sugestivním
                        autoportrétům také další autoři. Vojtěch Nolč bez velké malířské zkušenosti
                        namaloval sám sebe v jakési vězeňské místnosti v deliktní škále žlutí,
                        která jakoby prozrazovala jeho budoucí pokusy s malbou pod vlivem drog, ...
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>
