<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row" ></div>
            <div class="row" >
                <div class="col-sm-6">
                    <h3>
                        Umění je abstrakce, Česká vizuální kultura 60. let
                    </h3>
                    <h4>
                        Zdeněk Primus
                    </h4>         
                    <h5>
                        Katalog ke stejnojmenné výstavě přibližuje českou vizuální kulturu 60. let.
                    </h5>
                </div>
                <div class="col-sm-4">
                    <br/>
                    <img src="umenijeabstrakce.gif" />    
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">                 <hr/>     
                    <p>
                        <a href="obrazy/Umeni_je_abstrakce.jpg">
                            <img src="obrazy/thumbs/Umeni_je_abstrakce.jpg" alt="" style="height:300px">
                        </a>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-8">               
                    <p>
                        > Vojta Nolč byl jedním z členů prvního poválečného modernistického 
                        seskupeni Máj 57. Jako
                        mnoho jiných z této skupiny se i on na první výstavě v roce 1957
                        prezentoval figurativní malbou
                        a teprve na počátku šedesátých let přešel do abstrakce.
                        Ovšem do abstrakce popisné, založené
                        na přímé inspiraci přírodou. Mušle, choroši, ořechy, kameny,
                        ale i kaligrafie a ornament 
                        orientálních koberců či archaické znaky, které bud' jsou,
                        ale častěji nejsou, rozluštěny, což zvyšuje
                        jejich tajemnost, ho inspirovaly k bezmála reliéfní vysoké
                        struktuře tvarů v obraze. Aby toto téma
                        vyniklo, hledal Nolč adekvátní nosič, a našel jej ve
                        starých opotřebovaných dřevěných deskách
                        nebo dveřích, v materiálech nesoucích stopy lidské ruky,
                        lidské práce, bytí člověka a jeho příběhů.
                        Oproti tomu je mu obligátní rám s plátnem pouze něčím neutrálním.
                        Spojením historie přírody
                        a historie činnosti člověka vznikla v české abstraktní scéně nová narativní
                        rovina,
                        která byla pravděpodobně ceněna v době svého vzniku vice než dnes,
                        kdy se česká
                        kunsthistorie více zabývá jen krátkou vírou několika mála jedinců, věnujících se
                        abstrakci v letech 1958/9 až 1965. Umělci pracující abstraktně nebo na hranici 
                        abstrakce po tomto období jsou hodnoceni jako zpozdilci či dokonce jako
                        zbloudilci.
                    </p><p>
                        > Obraz-objekt, 1964 (?), jehož původní název dnes již není znám, vnímáme v prvním
                        okamžiku opravdu jako desku stolu či staré vysloužilé dveře. Skládá se ze tří letitých,
                        nestejně širokých, na rubu ve dvou místech spojených prken. Markantní jsou obě mezery
                        mezi prkny, které nechají prosvítat stěnu, na které je obraz-objekt zavěšen.
                        Tím vzniká nová, třetí kvalita. Distance mezi uměleckým dílem, které vytváří obraz
                        jiného, uměle vytvořeného světa, a realitou, stěnou, která je jeho příjemcem,
                        je odstraněna: reálná stěna prosvítá škvírami mezi prkny a původní, nyní zpracovaný
                        materiál je vrácen v jiné, nové, esteticky náročnější podobě lidskému obydlí, 
                        jehož utilitární součásti byl původně.
                    </p><p>
                        > Prkna jsou pomalována hnědou olejovou barvou, jejíž slabý nátěr nechává 
                        prosvítat stářím vystupující léta. Na několika místech je deska přetřena jen lakem. 
                        Na tyto vrstvy jsou domalovány „organické" znaky. tvary, které možná byly původně
                        prastarým písmem, jež už ale dnes nikdo nezná a které, přečkavše věky, změnilo podobu
                        stejně, jak se pozměnil i materiál, na němž je naneseno. Náhodně rozseté znaky jsou buď temně
                        rudé, nebo tmavě hnědé barvy. Béla Kolářová vytvářela o tři roky dříve, v roce 1961,
                        fotografickou technikou podobné znaky. Pootočíme-li umělý negativ Neznámé písmo, 1961, 
                        Bély Kolářové o 90', připomíná Nolčův obraz-objekt tak silně, jako by šlo o jeho předlohu.
                        Jejich množství lze
                        snadno spočítat, ale sotva mohou byt chápány jako nositelé myšlenky nebo nějaké zprávy. Spíš
                        se z nich stali svědci něčeho již neexistujícího, stejně jako se svědky stala prkna desky,
                        než obojí
                        dostalo nový smysl a novou estetickou kvalitu.
                        Nolč jako tvůrce této kvality ji pozdvihl či podtrhl
                        lištami, které simuluji rám, a tím tento objekt-obraz potvrdil jako umělecké dílo.
                        Potřebu haptické
                        kvality, která byla v době vzniku obrazu-objektu, v roce 1964 pro Nolče důležitá,
                        naplnil vysokou
                        strukturou malby. Ztracený název díla není překážkou pro
                        jeho pochopeni, možná že by naopak
                        jeho popisnost - jaké Nolč užíval --byla zbytečná.
                    </p>
                </div>                            
            </div>                            
        </div>
    </body>
</html>
