<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <a href="galerie/villon/villon1.jpg" class="thumbnail">
                        <img src="galerie/villon/thumbs/villon1.jpg" alt="Villon" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/villon/villon2.jpg" class="thumbnail">
                        <img src="galerie/villon/thumbs/villon2.jpg" alt="Villon" style="height:150px">
                    </a>
                </div>
                <div class="col-md-4">
                    <a href="galerie/villon/villon3.jpg" class="thumbnail">
                        <img src="galerie/villon/thumbs/villon3.jpg" alt="Villon" style="height:150px">
                    </a>
                </div>
            </div>          
        </div>            
    </body>
</html>
