<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h3>Vzpomínka Ondřeje Daněčka</h3>
                    <p>
                    </p><p>
                        Na Vojtu Nolče si matně pamatuji jako malý kluk, když jsme cca v roku 1953 možná 54 trávili
                        s rodiči dovolenou na ROH Chatě Státní Banky Československé na Slapech.
                        Vojta tam měl poblíž chatu (možná jen půjčenou) a my jsme k němu chodili
                        opékat buřty na táboráku.
                        Pamatuji si, že se choval velmi galantně k naší máti a k dámám vůbec.
                    </p><p>
                        Lepší vzpomínku mám cca z roku 1966-7. Táta mi domluvil u Vojty návštěvu
                        v ateliéru na Vinohradech
                        s tím, že se Mistr podívá na pár mých matlanic a odborně je posoudí.
                        Byly to většinou temperové
                        výkřiky vrcholící puberty, často abstraktní a Vojta na to chudák koukal
                        a nevěděl moc co říct,
                        protože mne asi nechtěl ranit, ale zároveň chválit to také nešlo.
                        Schodou okolností se přesně v tu samou dobu objevil
                        v ateliéru jistý bankovní úředník,
                        pan Jošt se synem, za úplně totožným účelem a sice,
                        aby Vojta posoudil talent a uměleckou hodnotu
                        výtvorů mladého Jošta, teenagera přibližně stejného
                        věku jako jsem byl já, tedy kolem 16ti.
                        Byly to precizní, realistické kresby tužkou a perem, nějaké historické či válečnické
                        výjevy ala František Burian.
                        No a Mistr tedy se chvíli
                        rozhlížel z jednoho nadělení na druhé, mnul si bradu
                        a pak pravil k panu Joštovi něco v tom smyslu,
                        že zde máme před sebou dvě krásné ukázky opačných stran tvůrčího spektra.
                        Na jedné straně povrchní,
                        barevné fantasmagorie bez disciplíny, bez poctivého základu
                        a tvrdé práce a na druhé straně poctivý,
                        úzkostlivě precizní, řemeslný proces ale postrádající invenci,
                        rebelii a špetku nutného bláznovství.
                    </p><p>
                        Tedy zde u Daněčka je třeba začít seriózně pracovat
                        a studovat řemeslnou stránku malování a u Jošta
                        naopak otevřít okenice a vzůru do mnohobarevné rozmanitosti života! 
                        My jsme s mladým Joštem ztrapněně rudli a bledli a já jsem byl nakonec moc rád,
                        když jsem se octnul
                        zpátky na ulici s deskama svých věcí podpaží,
                        že už jsem neokrádal skutečného kumštýře, pana Nolče o čas.
                        Závěrem uvádím, že to lovím z hlavy po témeř půl století a je 
                        to vše třeba brát s jistým zrnkem soli.
                        Taky bych rád řekl, že si zpětně vybavuji pocit úcty a obdivu,
                        který jsem k Vojtovi tehdy měl, pro jeho poctivou skromnost,
                        laskavost a dobrotu srdce, to vše na první pohled tolik evidentní.
                    </p>
                </div>
            </div>
        </div>
    </body>
</html>
