<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Vojta Nolč</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php include 'nav.inc'; ?>
        <div class="container">
            <div class="row">
                <div class="col-sm-8">
                    <h3>Mládí a počátky tvorby</h3>
                    <p>                   Vojta Nolč se narodil a vyrůstal v hornorakouském Linci.
                        Teprve po vzniku republiky se rodina přestěhovala do západních Čech. Mezi lety 1927 a 1931 studoval na
                        Německé obchodní akademii v Plzni. Od maturity až do konce 50. let pracoval jako bankovní úředník v Praze.
                        Výtvarné vzdělání získal soukromě u Aloise Boháče a Vladimíra Pukla. Věnoval se kresbě, malbě a společně s
                        tiskařem Adolfem Černým experimentoval s grafickými technikami. Na výtvarnou scénu vstoupil jako jeden ze
                        zakládajících členů tvůrčí skupiny Máj 57 hned při jejím prvním vystoupení v rámci společné výstavy
                        Mladé umění v pražském Obecním domě (1957). Představil se deseti pracemi - olejomalbou a monotypy - 
                        ze svého žlutého období ovlivněného francouzským postimpresionismem. Na výstavě, která v éře socialistického
                        realismu vzbudila rozruch požadavkem individuálního výrazu a návazností na moderní tendence 
                        mezinárodního umění, takže jí hrozilo uzavření, byl zmiňován mezi autory udávající charakter expozice1. 
                        V Máji 57, kde byl vůbec nejstarší, patřil zpočátku do okruhu kolem historika umění Františka Dvořáka a 
                        malíře Roberta Piesena, který jej do skupiny přivedl. Později se přimkl ke křídlu absolventů VŠUP, 
                        které reprezentovali Mikuláš Medek, Stanislav Podhrázký a Zbyněk Sekal. Se skupinou Nolč pravidelně
                        vystavoval až do jejího zániku v roce 1964.                </p> 

                    <h3> Umělecký vývoj během výstav v 60. letech</h3>
                    <p> První samostatná výstava tušových kreseb a monotypů Vojty Nolče v Divadle Rokoko (1959),
                        kterou uváděl právě skupinový teoretik František Dvořák, ještě volně rozvíjela působivou „naivizující“
                        polohu, kterou se předvedl v Obecním domě. Její těžiště stále spočívalo ve figuraci a především krajinných
                        a venkovských motivech – z prostředí slovenské Polany, západočeských Pavlovic a moravské Telče.
                        Druhá autorská výstava v Alšově síni v Praze (1964) už ale shrnovala proces intenzivního hledání nového
                        výtvarného výrazu. Nolč se v něm od „dětsky“ komponovaných plošně pojímaných pouťových motivů, dostal přes
                        postkubistickou urbánní skladebnost k sumárním prožitkovým „krajinám“. Ty intuitivně sestavoval z drobných 
                        lineárně rytých motivů  volně vířících v prostoru monochromního pozadí, takže evokují souhrn emotivních
                        útržků vizuálních vzpomínek. Jarmila Skalická v katalogu k výstavě celek přirovnává k estetice perských 
                        koberců2. Další mezifázi představují obrazy zaměřené na přírodniny zajímavé tvarem jako jsou ořechy nebo
                        mušle, které jen potvrzují Nolčův vzrůstající zájem o struktury. Ten ústí v abstrahující kompozice s 
                        geometrickým tvaroslovím odvozené z principu fragmentalizace. Třetí určující výstava Vojty Nolče proběhla
                        v pražské Galerii bří Čapků (1966). Představil se na ní především souborem vrstvených informelních kompozic
                        na masivních dřevěných podložkách poznamenaných působením času. Obrazy na pomezí objektu kombinovaly
                        přirozené a nově vytvářené struktury s principy znakovosti a lité malby. Ty doplňovala tématicky navazující
                        série velkoformátových monotypů. Toto období je u Nolče tradičně spojováno s experimenty s psychotropními
                        látkami3. Po roce 1970 se jeho pozornost obrátila k vytváření asambláží a pozvolnému návratu ke sféře
                        lidového umění, kdy se věnoval například malbě na sklo. Nově se u něj objevila náboženská témata,
                        ale neodvrátil se ani od civilismu.                  
                    </p>
                    <h3>Romantismus Vojty Nolče</h3>
                    <p>Vojta Nolč představuje na naší výtvarné scéně zdánlivě lehce anachronický, ale přitom  svébytný
                        a tím i velmi zajímavý fenomén, což také odráží postupné zařazování jeho prací do zásadních přehledových 
                        výstav monitorujících moderní české umění 50. a 60. let 20. století. Typický je pro něj originální
                        přístup opřený o vlastní logiku, charakteristický hlavně intuitivním příklonem k romantismu,
                        který se u něj projevuje různými způsoby po celou dobu tvorby. Ukazuje na něj např. povangoghštělé
                        signování pouze křestním jménem při žlutém období, obsáhlý cyklus procítěných kreseb na námět 
                        Villonova Malého a Velkého testamentu, téma cirkusu, poutí a kočovných komediantů,
                        i výtvarný proces směřující k abstrakci prostřednictvím ponoru do sféry archaického světa –
                        tajemných orientálních znaků, časem setřelých reliéfů, neidentifikovatelných fragmentů z
                        archeologických vykopávek nebo struktur založených na dlouholetém působení přírodních procesů.
                        Neprotiřečí mu nakonec ani pozdní asambláže evokující alchymistické strojky a zapomenuté vynálezy
                        či okouzlení nehledaným výrazem lidového umění. Jak ale ukazuje žlutý Autoportrét za rudými mříženi
                        z 50. let nebo monotyp Ohnivá pravda (Jan Palach), nevyhýbal se Nolč ani reflexi zcela aktuálních
                        životních pocitů a politických témat.                                        
                    </p>
                    <p class="text-right">Radek Wohlmuth</p>
                </div>
            </div>
        </div>
    </body>
</html>
